use_frameworks!

platform :ios, '8.0'

target 'HZSHookVCBack_Example' do
  pod 'HZSHookVCBack', :path => '../'

  target 'HZSHookVCBack_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
